version: "3.2"

services:
  oedb-compile:
    image: kherring/oedb:latest
    container_name: oedb-compile
    volumes:
      - ./:/home/pscadmin/project
      - ${DLC}/progress.cfg:/psc/dlc/progress.cfg:ro
    entrypoint: 'ant compile test'
    secrets:
      - PROGRESS_CFG
    profiles:
      - compile

  oedb:
    image: kherring/oedb:latest
    container_name: oedb
    environment:
      - DB_CREATE_METHOD=none
      - DB_DIR=sp2k
      - DB_NAME=sp2k
      - DB_BROKER_PORT=2500
      - DB_MINPORT=2600
      - DB_MAXPORT=2699
    # network_mode: host
    ports:
      - '127.0.0.1:2500:2500'
      - '127.0.0.1:2600-2699:2600-2699'
    volumes:
      - ${DLC}/progress.cfg:/psc/dlc/progress.cfg:ro
    secrets:
      - PROGRESS_CFG
    profiles:
      - run_db

secrets:
  PROGRESS_CFG:
    file: c:/Progress/OpenEdge/progress.cfg
