version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  # build-container:
  compile-and-test:
    docker:
      - image: kherring/oedb:latest
    steps:
      - checkout
      - run:
          name: ant compile
          command: |
            set -x
            mkdir -p secrets
            .circleci/hex2bin.sh \<<< "$(tr ' ' '\n' \<<< "$PROGRESS_CFG_HEX")" > /psc/dlc/progress.cfg
            
            ant compile
      - run: ant test
      - persist_to_workspace:
          root: .
          paths: [ '.' ]
  sonar-scan:
    docker:
      - image: cimg/openjdk:11.0.20
    steps:
      - attach_workspace:
          at: .
      - sonarcloud/scan
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - compile-and-test
      - sonar-scan:
          requires: [ compile-and-test ]
          context: SonarCloud
